services:
  - type: web
    name: n8n-on-render
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: with-worth admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "*with-worth@admin#"
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n-on-render.onrender.com
      - key: NODE_OPTIONS
        value: --dns-result-order=ipv4first
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_CONNECTION_URL
        value: postgresql://postgres:dEf.HQ.Ynfww38m@db.zqjlhrdisvaembbqgolz.supabase.co:5432/postgres
